// book-store-frontend-vue/src/views/SignupComponent.vue
   <!-- <template>
    <div class="signup-container">
      <div class="signup-content">
        <h1>Sign Up</h1>
        <form @submit.prevent="submitForm">
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" class="form-control" v-model="formData.name" required />
          </div>
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" class="form-control" v-model="formData.username" required />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" class="form-control" v-model="formData.password" required />
          </div>
          <div class="form-group">
            <label for="confirm-password">Confirm Password</label>
            <input type="password" id="confirm-password" class="form-control" v-model="formData.confirmPassword"
              required />
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </form>
      </div>
    </div>
  </template>

<script>
export default {
  name: 'SignupComponent',
  data() {
    return {
      formData: {
        name: '',
        username: '',
        password: '',
        confirmPassword: ''
      }
    };
  },
  methods: {
    submitForm() {
      // Handle form submission logic here (e.g., validation, API calls)
      console.log('Form submitted:', this.formData);
    }
  }
};
</script>

<style scoped>
.signup-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: url('../assets/WhiteLibrary.png') no-repeat center center/cover;
}

.signup-content {
  max-width: 400px;
  width: 100%;
  padding: 30px;
  background-color: rgb(200, 164, 164);
  border-radius: 8px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  color: #222;

}

.signup-content h1 {
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  font-weight: bold;
}

.form-control {
  width: 100%;
  padding: 10px;
  font-size: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.btn-primary {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  font-size: 1rem;
  cursor: pointer;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.terms {
  margin-top: 20px;
  font-size: 0.875rem;
}

.terms a {
  color: #007bff;
  text-decoration: none;
}

.terms a:hover {
  text-decoration: underline;
}
</style>
 -->

 <!-- <template>
  <div class="signup-container">
    <div class="signup-content">
      <h1>Sign Up</h1>
      <form @submit.prevent="submitForm">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" id="name" class="form-control" v-model="formData.name" required />
        </div>
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" class="form-control" v-model="formData.username" required />
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="text" id="email" class="form-control" v-model="formData.email" required />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" class="form-control" v-model="formData.password" required />
        </div>
        <div class="form-group">
          <label for="confirm-password">Confirm Password</label>
          <input type="password" id="confirm-password" class="form-control" v-model="formData.confirmPassword" required />
        </div>
        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
      </form>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'SignupComponent',
  data() {
    return {
      formData: {
        userId: 0,
        roleId: 2,
        name: '',
        username: '',
        email: '',
        password: '',
        confirmPassword: '',
        dateOfBirth: '2024-07-29T10:13:00.053Z', // default value or could be updated
        phoneNumber: '' // default value or could be updated
      }
    };
  },
  methods: {
    async submitForm() {
      if (this.formData.password !== this.formData.confirmPassword) {
        alert('Passwords do not match');
        return;
      }

      const requestPayload = {
        userId: this.formData.userId,
        name: this.formData.name,
        roleId:this.formData.roleId,
        username: this.formData.username,
        dateOfBirth: this.formData.dateOfBirth,
        phoneNumber: this.formData.phoneNumber,
        email: `${this.formData.username}@example.com`, // default or use an actual email field if you add one
        passwordHash: this.formData.password // Adjust this if your backend expects a hashed password
      };

      try {
        const response = await axios.post('https://localhost:7044/api/Auth/Register', requestPayload);
        console.log('Registration successful:', response.data);
        // Handle success, e.g., redirect to login page
      } catch (error) {
        console.error('Registration failed:', error.response ? error.response.data : error.message);
        // Handle error, e.g., show an error message to the user
      }
    }
  }
};
</script> -->

<template>
  <div class="signup-container">
    <div class="signup-content">
      <h1>Sign Up</h1>
      <form @submit.prevent="submitForm">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" id="name" class="form-control" v-model="formData.name" required />
        </div>
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" class="form-control" v-model="formData.username" required />
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="text" id="email" class="form-control" v-model="formData.email" required />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" class="form-control" v-model="formData.password" required />
        </div>
        <div class="form-group">
          <label for="confirm-password">Confirm Password</label>
          <input type="password" id="confirm-password" class="form-control" v-model="formData.confirmPassword" required />
        </div>
        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
      </form>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import Toastify from 'toastify-js';
import 'toastify-js/src/toastify.css'; // Import Toastify CSS

export default {
  name: 'SignupComponent',
  data() {
    return {
      formData: {
        userId: 0,
        roleId: 2,
        name: '',
        username: '',
        email: '',
        password: '',
        confirmPassword: '',
        dateOfBirth: '2024-07-29T10:13:00.053Z', // default value or could be updated
        phoneNumber: '' // default value or could be updated
      }
    };
  },
  methods: {
    async submitForm() {
      if (this.formData.password !== this.formData.confirmPassword) {
        Toastify({
          text: 'Passwords do not match',
          backgroundColor: "linear-gradient(to right, #ff5f6d, #ffc371)",
          duration: 3000,
          close: true
        }).showToast();
        return;
      }

      const requestPayload = {
        userId: this.formData.userId,
        name: this.formData.name,
        roleId: this.formData.roleId,
        username: this.formData.username,
        dateOfBirth: this.formData.dateOfBirth,
        phoneNumber: this.formData.phoneNumber,
        email: this.formData.email, // Use the actual email field
        passwordHash: this.formData.password // Adjust if your backend expects a hashed password
      };

      try {
        const response = await axios.post('https://localhost:7044/api/Auth/Register', requestPayload);
        console.log('Registration successful:', response.data);
        // Handle success, e.g., redirect to login page
        Toastify({
          text: 'Registration successful! Please log in.',
          backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
          duration: 3000,
          close: true
        }).showToast();
        this.$router.push('/login'); // Redirect to login page after successful registration
      } catch (error) {
        console.error('Registration failed:', error.response ? error.response.data : error.message);
        Toastify({
          text: error.response ? error.response.data.message : 'An error occurred during registration.',
          backgroundColor: "linear-gradient(to right, #ff5f6d, #ffc371)",
          duration: 3000,
          close: true
        }).showToast();
      }
    }
  }
};
</script>


<style scoped>
.signup-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: url('../assets/WhiteLibrary.png') no-repeat center center/cover;
}

.signup-content {
  max-width: 400px;
  width: 100%;
  padding: 30px;
  background-color: rgb(200, 164, 164);
  border-radius: 8px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  color: #222;
}

.signup-content h1 {
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  font-weight: bold;
}

.form-control {
  width: 100%;
  padding: 10px;
  font-size: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.btn-primary {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  font-size: 1rem;
  cursor: pointer;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.terms {
  margin-top: 20px;
  font-size: 0.875rem;
}

.terms a {
  color: #007bff;
  text-decoration: none;
}

.terms a:hover {
  text-decoration: underline;
}
</style>

// BookStoreFrontEnd/src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { UserDTO } from 'src/app/services/user.dto';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent {
  formData: UserDTO = new UserDTO();
  confirmPassword: string = '';

  constructor(private http: HttpClient,private router:Router) {}

  submitForm(): void {
    if (this.validateForm()) {
      const userData = {
        username: this.formData.username,
        email: this.formData.email,
        roleId:this.formData.roleId,
        passwordHash: this.formData.password
      };

      // Replace 'http://your-backend-api-url/register' with your actual backend API endpoint
      this.http.post('http://localhost:5134/api/Users', userData)
        .subscribe(
          response => {
            console.log('User registration successful:', response);
            this.resetForm();
            this.router.navigate(['/home']);

          },
          error => {
            console.error('Error registering user:', error);
            // Handle error accordingly
          }
        );
    }
  }

  validateForm(): boolean {
    if (this.formData.password !== this.confirmPassword) {
      alert('Passwords do not match');
      return false;
    }
    return true;
  }

  resetForm(): void {
    this.formData.username = '';
    this.formData.email = '';
    this.formData.password = '';
    this.confirmPassword = '';
  }
}

<div class="signup-container">
    <div class="signup-content">
      <h1>Registration</h1>
      <form (ngSubmit)="submitForm()">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" class="form-control" [(ngModel)]="formData.username" name="username" required />
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" id="email" class="form-control" [(ngModel)]="formData.email" name="email" required />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" class="form-control" [(ngModel)]="formData.password" name="password" required />
        </div>
        <div class="form-group">
          <label for="confirm-password">Confirm Password</label>
          <input type="password" id="confirm-password" class="form-control" [(ngModel)]="confirmPassword" name="confirmPassword" required />
        </div>
        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
      </form>
    </div>
  </div>
