// book-store-frontend-vue/src/components/CarouselComponent.vue
<template>
  <div class="carousel-container">
    <div class="carousel-slides" :style="{'transform': 'translateX(-' + (currentSlideIndex * 100) + '%)'}">
      <div class="carousel-slide" v-for="(slide, i) in carouselSlides" :key="i" :class="{'active': i === currentSlideIndex}">
        <img :src="require(`../../public/c${i + 1}.png`)" :alt="slide.caption">
        <div class="carousel-caption">{{ slide.caption }}</div>
      </div>
    </div>
    <button class="carousel-control prev" @click="prevSlide()">&#10094;</button>
    <button class="carousel-control next" @click="nextSlide()">&#10095;</button>
    <div class="carousel-indicators">
      <span v-for="(slide, i) in carouselSlides" :key="i" :class="{'active': i === currentSlideIndex}" @click="goToSlide(i)"></span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'CarouselComponent',
  data() {
    return {
      carouselSlides: [
        { caption: 'Heavy Discount' },
        { caption: 'New Additions' },
        { caption: 'Summer Sale' }
      ],
      currentSlideIndex: 0,
      intervalId: null
    };
  },
  mounted() {
    if (this.carouselSlides.length > 0) {
      this.startAutoSlide();
    }
  },
  beforeUnmount() {
    clearInterval(this.intervalId);
  },
  methods: {
    startAutoSlide() {
      this.intervalId = setInterval(() => {
        this.nextSlide();
      }, 3000); // Change slide every 3 seconds
    },
    nextSlide() {
      this.currentSlideIndex = (this.currentSlideIndex + 1) % this.carouselSlides.length;
    },
    prevSlide() {
      this.currentSlideIndex = (this.currentSlideIndex - 1 + this.carouselSlides.length) % this.carouselSlides.length;
    },
    goToSlide(index) {
      this.currentSlideIndex = index;
    }
  }
};
</script>

<style scoped>
.carousel-container {
  position: relative;
  overflow: hidden;
  width: 100%;
  max-width: 100%;
  border: 1px solid #ddd;
  border-radius: 5px;
}

.carousel-slides {
  display: flex;
  transition: transform 0.5s ease;
  width: 100%;
}

.carousel-slide {
  min-width: 100%;
  box-sizing: border-box;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
}

.carousel-slide img {
  width: 100%;
  height: auto;
}

.carousel-caption {
  position: absolute;
  bottom: 10px;
  left: 20px;
  background: rgba(0, 0, 0, 0.5);
  color: #fff;
  padding: 10px;
  border-radius: 5px;
}

.carousel-control {
  position: absolute;
  top: 50%;
  width: 40px;
  height: 40px;
  background: rgba(0, 0, 0, 0.5);
  color: #fff;
  border: none;
  cursor: pointer;
  font-size: 24px;
  text-align: center;
  line-height: 40px;
  border-radius: 50%;
  transform: translateY(-50%);
  z-index: 1000;
}

.prev {
  left: 10px;
}

.next {
  right: 10px;
}

.carousel-indicators {
  position: absolute;
  bottom: 10px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 5px;
}

.carousel-indicators span {
  width: 10px;
  height: 10px;
  background: #ddd;
  border-radius: 50%;
  cursor: pointer;
}

.carousel-indicators .active {
  background: #333;
}
</style>

// BookStoreFrontEnd/src/app/components/carousel/carousel.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.scss']
})
export class CarouselComponent implements OnInit, OnDestroy {

  // Static data for the carousel slides
  carouselSlides = [
    { image: '/assets/images/baner/fictionBaner.png', caption: 'Fiction Books' },
    { image: '/assets/images/baner/offerBaner.png', caption: 'Special Offers' },
    { image: '/assets/images/baner/SummerSale.png', caption: 'Summer Sale' }
  ];

  currentSlideIndex: number = 0;
  intervalId?: any;

  ngOnInit(): void {
    if (this.carouselSlides.length > 0) {
      this.startAutoSlide();
    }
  }

  ngOnDestroy(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  startAutoSlide(): void {
    this.intervalId = setInterval(() => {
      this.nextSlide();
    }, 3000); // Change slide every 3 seconds
  }

  nextSlide(): void {
    this.currentSlideIndex = (this.currentSlideIndex + 1) % this.carouselSlides.length;
  }

  prevSlide(): void {
    this.currentSlideIndex = (this.currentSlideIndex - 1 + this.carouselSlides.length) % this.carouselSlides.length;
  }

  goToSlide(index: number): void {
    this.currentSlideIndex = index;
  }
}

<div class="carousel-container">
    <div class="carousel-slides" [ngStyle]="{'transform': 'translateX(-' + (currentSlideIndex * 100) + '%)'}">
      <div class="carousel-slide" *ngFor="let slide of carouselSlides; let i = index" [ngClass]="{'active': i === currentSlideIndex}">
        <img [src]="slide.image" [alt]="slide.caption">
        <!-- <div class="carousel-caption">{{ slide.caption }}</div> -->
      </div>
    </div>
    <button class="carousel-control prev" (click)="prevSlide()">&#10094;</button>
    <button class="carousel-control next" (click)="nextSlide()">&#10095;</button>
    <div class="carousel-indicators">
      <span *ngFor="let slide of carouselSlides; let i = index" [ngClass]="{'active': i === currentSlideIndex}" (click)="goToSlide(i)"></span>
    </div>
  </div>
