// BookStoreFrontEnd/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  isLoggedIn: boolean = false;

  constructor(private http: HttpClient, private router: Router) {}

  onSubmit() {
    const apiUrl = 'http://localhost:5134/api/auth/authenticate';
    const body = {
      username: this.username,
      password: this.password
    };

    this.http.post(apiUrl, body).subscribe(
      (response: any) => {
        // Handle successful authentication here (e.g., store token in localStorage)
        console.log('Authentication successful');
        console.log('Token:', response.token);

        // Store token in localStorage (example)
        localStorage.setItem('token', response.token);

        // Set isLoggedIn flag to true
        this.isLoggedIn = true;

        // Redirect to home page
        this.router.navigate(['/home']);
      },
      (error) => {
        // Handle authentication error (e.g., display error message)
        console.error('Authentication error:', error);
      }
    );
  }

  logout() {
    // Clear localStorage or perform logout actions
    localStorage.removeItem('token');
    this.isLoggedIn = false;
  }
}

<div class="login-container">
  <!-- <img src="../assets/girlreading.png" alt="Login Image" class="girl"> -->
  <div class="form-container">
    <!-- <img src="../assets/PustakParadise.png" alt="Login Image" class="logoimage"> -->
    <p class="subtitle">Login to your account</p>
    <form (ngSubmit)="onSubmit()" class="login-form">
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" [(ngModel)]="email" required />
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" [(ngModel)]="password" placeholder="Password" required>
      </div>
      <button type="submit" *ngIf="!isLoggedIn">LOGIN</button>
      <button type="button" (click)="logout()" *ngIf="isLoggedIn">Logout</button>
    </form>
    
    <div class="links">
      <p>
        <a href="/home/forgotpassword">Forgot Password ?</a>
      </p>
      <!-- <a href="#" class="forgot-password">Forgot password?</a> -->
      <p>
        Don't have an account? <a href="home/signup">Register here</a>
      </p>
      <p class="terms">
        <a href="#">Terms of use</a>     &nbsp;<a href="#">Privacy policy</a>
      </p>
    </div>
  </div>
</div>




<!-- <div class="login-container">
  <img src="../assets/girlreading.png" alt="Login Image" class="girl">
  <div class="form-container">
    <img src="../assets/PustakParadise.png" alt="Login Image" class="logoimage">
    <p class="subtitle">Login to your account</p>
    <form (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" [(ngModel)]="username" required />
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" [(ngModel)]="password" required />
      </div>
      <button type="submit" *ngIf="!isLoggedIn">LOGIN</button>
      <button type="button" (click)="logout()" *ngIf="isLoggedIn">Logout</button>
    </form>
    <div class="links">
      <a href="#" class="forgot-password">Forgot password?</a>
      <p>
        Don't have an account? <a href="/signup">Register here</a>
      </p>
      <p class="terms">
        <a href="#">Terms of use</a>. <a href="#">Privacy policy</a>
      </p>
    </div>
  </div>
</div> -->




<!-- <div>
  <h2>Login</h2>
  <form (ngSubmit)="onSubmit()">
    <div>
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" [(ngModel)]="username" required>
    </div>
    <div>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" [(ngModel)]="password" required>
    </div>
    <button type="submit" *ngIf="!isLoggedIn">Login</button>
    <button type="button" (click)="logout()" *ngIf="isLoggedIn">Logout</button>
  </form>
</div> -->

// book-store-frontend-vue/src/views/LoginComponent.vue
<template>
  <div class="login-container">
    <img src="../assets/girlreading.png" alt="Login Image" class="girl">
    <div class="form-container">
      <img src="../assets/PustakParadise.png" alt="Login Image" class="logoimage">
      <p class="subtitle">Login to your account</p>
      <form @submit.prevent="login">
        <div class="form-group">
          <input type="email" id="email" v-model="email" placeholder="Email address" required />
        </div>
        <div class="form-group">
          <input type="password" id="password" v-model="password" placeholder="Password" required />
        </div>
        <button type="submit">LOGIN</button>
      </form>
      <div class="links">
        <a href="#" class="forgot-password">Forgot password?</a>
        <p>
          Don't have an account? <a href="/signup">Register here</a>
        </p>
        <p class="terms">
          <a href="#">Terms of use</a>. <a href="#">Privacy policy</a>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import Toastify from 'toastify-js';
import 'toastify-js/src/toastify.css'; // Import Toastify CSS

export default {
  name: 'LoginComponent',
  data() {
    return {
      email: '',
      password: '',
    };
  },
  methods: {
    async login() {
      try {
        const response = await axios.post('https://localhost:7044/api/Auth/Login', {
          email: this.email,
          password: this.password,
        });
        
        // Handle successful login
        console.log('Login successful:', response.data);

        // Example: Store token
        localStorage.setItem('authToken', response.data.token);

        // Check user role and redirect
        if (response.data.roleId === 1) {
          this.$router.push('/adminview'); // Redirect to admin view
        } else {
          this.$router.push('/home'); // Redirect to default user dashboard
        }
      } catch (error) {
        // Handle error with Toastify
        console.error('Login failed:', error.response ? error.response.data : error.message);
        Toastify({
          text: error.response ? error.response.data.message : 'An error occurred during login.',
          backgroundColor: "linear-gradient(to right, #ff5f6d, #ffc371)",
          duration: 3000,
          close: true
        }).showToast();
      }
    },
  },
};
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #9b596b;
}

.image-container {
  display: none;
  /* Hide for smaller screens */
}

.image-container img {
  width: 400px;
  border-radius: 10px;
}

.form-container {
  background: #fff;
  padding: 40px 30px;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  max-width: 400px;
  width: 100%;
}

.logo {
  margin-bottom: 10px;
  font-size: 24px;
  font-weight: bold;
  text-align: center;
}

.subtitle {
  margin-bottom: 20px;
  text-align: center;
  color: #666;
}

.form-group {
  margin-bottom: 20px;
}

.form-group input {
  width: 100%;
  padding: 10px;
  font-size: 16px;
  border: 1px solid #ddd;
  border-radius: 5px;
}

button {
  width: 100%;
  padding: 10px;
  background: #333;
  color: #fff;
  font-size: 16px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

button:hover {
  background: #555;
}

.links {
  margin-top: 20px;
  text-align: center;
}

.links a {
  color: #007bff;
  text-decoration: none;
}

.links a:hover {
  text-decoration: underline;
}

.terms {
  margin-top: 10px;
  color: #666;
}

.forgot-password {
  display: block;
  margin-bottom: 10px;
}

.logoimage {
  height: 150px;
}
</style>
